config/routes.rb
Rails.application.routes.draw do

  # Take the user to their surveys. This will handle new users as well.
  root 'surveys#index'

  delete '/logout', to: 'users#logout_user'

  get '/surveys/send', to: 'surveys#send_survey'
  get '/responses/send', to: 'responses#send_receipt'

  get '/surveys/:token', to: 'responses#new'

  #put '/sidebar/questions/:id', to: 'sidebar#update'

  #namespace admin
  
  resources :users do
    resources :surveys
  end

  resources :surveys do
    resources :questions
    resources :responses
  end

  resources :questions do
    resources :choices
    resources :answers
  end

  resources :choices do
    resources :questions
  end

  resources :answers do
    resources :choices
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<!--<div class="footer container-fluid">
	<h1>Footer</h1>	
</div>-->

app/views/shared/_header.html.erb
<nav class="navbar navbar-toggleable-sm navbar-light">

  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!--<a class="navbar-brand" href="#">Jestick</a>-->

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if logged_in? %>
        <!-- <li class="nav-item">< link_to "Home", new_user_survey_path(current_user.id), :class => "nav-link" %></li> -->
<!--         <li class="nav-item">< link_to "Account", user_path(current_user.id), :class => "nav-link" %></li> -->
        <li class="nav-item"><%= link_to "Surveys", user_surveys_path(current_user.id), :class => "nav-link" %></li>                      
        <li class="nav-item"><%= link_to "Logout", logout_path, method: :delete, :class => "nav-link" %></li>
      <% else %>
        <li class="nav-item"><%= link_to "Login/Signup", new_user_path, :class => "nav-link" %></li>
      <% end %>
    </ul>
  </div>
</nav>