config/routes.rb
Rails.application.routes.draw do

  # Take the user to their surveys. This will handle new users as well.
  root 'surveys#index'

  delete '/logout', to: 'users#logout_user'

  get '/surveys/send', to: 'surveys#send_survey'
  get '/responses/send', to: 'responses#send_receipt'

  get '/surveys/:token', to: 'responses#new'

  #put '/sidebar/questions/:id', to: 'sidebar#update'

  #namespace admin
  
  resources :users do
    resources :surveys
  end

  resources :surveys do
    resources :questions
    resources :responses
  end

  resources :questions do
    resources :choices
    resources :answers
  end

  resources :choices do
    resources :questions
  end

  resources :answers do
    resources :choices
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/survey.rb
class Survey < ApplicationRecord
  belongs_to :user
  
  has_many :responses, dependent: :destroy
  has_many :questions, dependent: :destroy

end

app/controllers/surveys_controller.rb
require('securerandom')

class SurveysController < ApplicationController
  before_action :find_survey, only: [:show, :edit, :update, :destroy, :send_survey]

  def index
    #Look up surveys for the current user
    @surveys = Survey.where(user_id: current_user.id)
    @survey = Survey.new

  end

  def create

    @survey = Survey.create(user_id: current_user.id, title: params[:survey][:title], title_color: "black", description: "Description", color: "#CBE068", token: SecureRandom.uuid, is_active: false)
    #redirect_to user_surveys_path(current_user.id)
    #http://guides.rubyonrails.org/working_with_javascript_in_rails.html
    respond_to do |format|

      format.html { redirect_to user_surveys_path(current_user.id) }
      format.js {}
      format.json { render json: @survey, status: :created, location: @survey }

      # format.html { render action: 'new' }
      # format.json { render json: @survey.errors, status: :unprocessable_entity }

    end

  end

  def show
    @questions = Question.where(survey_id: @survey.id, choice_id: nil)    
  end

  def edit
    @questions = Question.where(survey_id: @survey.id, choice_id: nil)
  end

  def update

    @survey.update(survey_params)

    #http://guides.rubyonrails.org/working_with_javascript_in_rails.html
    respond_to do |format|

      format.html { redirect_to user_surveys_path(current_user.id) }
      format.js {}
      format.json { render json: @survey, status: :created, location: @survey }

      # format.html { render action: 'new' }
      # format.json { render json: @survey.errors, status: :unprocessable_entity }

    end

  end

  def destroy

    @survey.destroy
    redirect_to user_surveys_path(current_user.id)

  end

  def send_survey

    SurveyMailer.send_survey(@survey, "sender_email", params[:recipients].split(';')).deliver_later;
    redirect_to user_surveys_path(current_user.id)

  end

  private
    def survey_params
      params.require(:survey).permit(:title, :description, :color, :title_color, :is_active)
    end

    def find_survey
      @survey = current_user.surveys.find(params[:id])
    end

end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_new.html.erb
<%= form_for(@survey, url: { action: "create", remote: true }) do |f| %>
	<div class="form-group row">
		<div class="col-6">
			<%= f.text_field(:title, {class: 'form-control', placeholder: 'Survey Title', value: 'New Survey'}) %>
		</div>
		<div class="col-6">
			<%= f.submit("Add New Survey", {class: 'btn btn-primary'}) %>
		</div>
	</div>
<% end %>

app/views/surveys/_survey.html.erb
<div class="col-1">
	<%= survey.color %>
</div>
<div class="col-3">
	<%= survey.title %>
</div>
<div class="col-4">
	<%= survey.token %>
</div>
<div class="col-2">
	<%= survey.is_active %>
</div>
<div class="col-1">
	<%= link_to "Edit", edit_user_survey_path(current_user.id, survey.id) %>
</div>
<div class="col-1">
	<%= link_to "Delete", user_survey_path(current_user.id, survey.id), method: :delete %>
</div>

app/views/surveys/_survey_headers.html.erb
<div class="col-1">
	<h2>Color</h2>
</div>
<div class="col-3">
	<h2>Title</h2>
</div>
<div class="col-4">
	<h2>Token</h2>
</div>
<div class="col-2">
	<h2>Active</h2>
</div>

app/views/surveys/create.js.erb
// Ask Aaron about the shortcut to escape_javascript; just j?
$("<%= escape_javascript(render @survey) %>").appendTo("#surveys");

app/views/surveys/edit.html.erb
<style>
  #survey-title-box {
 	  background-color: <%= @survey.color %>;
  }
  #survey-title, #survey-title-color {
  	color: <%= @survey.title_color %>;
  }
</style>

<div class="container-fluid fill">
	<div class="row no-gutters fill-min">

		<div class="col-8 offset-1 survey" id="survey-<%= @survey.id %>">

      <!-- Survey title box and title -->
			<div class="row no-gutters align-items-center highlight" id="survey-title-box">
					<div class="col-1" id="survey-title-color-col">
						<span id="survey-title-color" class="highlight"><%= @survey.title_color %></span>
					</div>
					<div class="col-10 highlight" id="survey-title-col">
						<div id="survey-title" ><%= @survey.title %></div>
					</div>
					<div class="col-1 highlight" id="survey-color-box">
						<div id="survey-color"><%= @survey.color %></div>
					</div>
			</div>

			<!-- Survey Description -->
			<div class="row no-gutters" id="survey-description-row">
				<div class="col-10 offset-1 highlight">
					<div class="fill-width" id="survey-description"><%=@survey.description%></div>
				</div>
			</div>
			
      <!-- Survey questions -->
			<div class="row no-gutters align-items-center" id="survey-questions">
				<%= render partial: "questions/question_box/question_box", collection: @questions, locals: { question_box_type: 'parent' } %>
			</div>
			<div class="row no-gutters align-items-center" id="new-question">
				<%= render partial: "questions//question_box/new_question_box", locals: { survey: @survey, choice_id: "none" } %>
			</div>

		</div>

		<%= render partial: "sidebar/sidebar", locals: { survey: @survey } %>
		
	</div>
</div>	

app/views/surveys/index.html.erb
<div class="container fill">

	<h1>Survey List</h1>
	<!-- Try out a table here -->
	<div class="row">
		<%= render 'survey_headers' %>
	</div>
	<div class="row" id="surveys">
		<%= render @surveys %>
	</div>


	<div class="row align-items-center">

		<div class="col-6 offset-3" id="create-survey">

			<%= render 'new' %>

		</div>

	</div>
</div>

app/views/surveys/show.html.erb
<style>
  #survey-title-box-display {
    background-color: <%= @survey.color %>;
  }
  #survey-title-display {
    color: <%= @survey.title_color %>;
  }
</style>

<div class="container-fluid fill open-sans">
  <div class="row no-gutters fill-min">

    <div class="col-1" id="back-col">
      <i><%=link_to "", edit_user_survey_path(current_user.id, @survey.id) ,{ class: "fa fa-chevron-circle-left"}%></i>
    </div>

    <div class="col-8" id="survey-display">

      <!-- Survey title box and title -->
      <div class="row no-gutters align-items-center" id="survey-title-box-display">
          <div class="col-10 offset-1">
            <div id="survey-title-display"><%= @survey.title %></div>
          </div>
      </div>

      <!-- Survey Description -->
      <div class="row no-gutters align-items-center" id="survey-description-row-display">
        <div class="col-10 offset-1">
          <div class="fill-width"><%=@survey.description%></div>
        </div>
      </div>

      <div class="row no-gutters" id="email-row-display">
          <div class="col-10 offset-1">
            <input class="fill-width" id="email-display" type="text" name="email"/>
          </div>
          <div class="col-10 offset-1">
            <label for="email-display">Email</label>
          </div>          
      </div>
      
      <!-- Survey questions -->
      <div class="row no-gutters align-items-center">
        <%= render partial: "display/questions/question", collection: @questions, locals: { question_type: 'parent' } %>
      </div>

      <div class="row no-gutters" id="submit-survey-display">
        <div class="col-2 offset-1">
          <button>SUBMIT</button>
        </div>
      </div>

    </div>

    <div class="col-3" id="sidebar-display">
      <%= render partial: "display/sidebar/sidebar", locals: { survey: @survey } %>
    </div>
  </div>
</div>  